### ISSUE TITLE
gulp audio

### ISSUE THREAD

**Issue by marc-moreaux** [epic-kitchens/epic-lib#82]
Hello,

Would it make sense to Gulp audio too ?
I'm doing it, but I wonder if there is a specific reason not to do it...

**Comment by willprice** [comment]
Hi @marc-moreaux,
Sure, that seems sensible to me. I'd only worked with RGB and flow. @ekazakos is using audio with EPIC, I don't think he's using `gulpio`, but he might have some advice to share.

`gulpio` has two main benefits:
- Improved sequential read performance for spinning disks
- Fewer files that directories of images (improves reading and copying performance)

`torchvision` has recently added support for video with audio decoding, this might be of interest to you if you're setting up a new pipeline. One disadvantage is that you can only sample using PTS (presentation timestamps) rather than frame numbers. 

If you're computing spectrograms then you probably want to store those images rather than computing them on the fly. Although maybe computing them on the fly isn't so bad since torchaudio leverage's [`torch.stft`](https://pytorch.org/docs/stable/torch.html#torch.stft) for computing the Fourier` transform which could be done on the GPU--maybe that's quicker than loading the image on the GPU!
